name = "Treeque"
uuid = "cfd42080-4670-40bd-8d0e-f97b88df8fc1"
authors = ["Yelyzaveta Velizhanina <yelyzaveta.velizhanina@ulb.be> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
